# Generated by Django 3.2 on 2024-01-19 10:06

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240119_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(10, 'Оценка не может быть выше 10')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(help_text='Введите год, который не превышает текущий.', validators=[reviews.validators.year_validator], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Недопустимый символ!', regex='^[\\w.@+-]+\\Z'), reviews.validators.validate_username], verbose_name='Имя пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='reviews_review_unique_review'),
        ),
    ]
